//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by StorageClassGenerator
//
//     Do not change code in this file, it will get lost when the file gets 
//     auto generated again. Write your code into DC.cs.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Threading;
using Storage;


namespace StorageModel  {

  /// <summary>
  /// A part of DC is static, which gives easy access to all stored data (=context) through DC.Data. But most functionality is in the
  /// instantiatable part of DC. Since it is instantiatable, is possible to use different contexts over the lifetime of a program. This 
  /// is helpful for unit testing. Use DC.Init() to create a new context and dispose it with DisposeData() before creating a new one.
  /// </summary>
  public partial class DC: IDisposable {

    #region static Part
    //      -----------

    /// <summary>
    /// Provides static root access to the data context
    /// </summary>
    public static DC Data {
      get { return data!; }
    }
    private static DC? data; //data is needed for Interlocked.Exchange(ref data, null) in DisposeData()


    /// <summary>
    /// Flushes all data to permanent storage location if permanent data storage is active. Compacts data storage
    /// by applying all updates and removing all instances marked as deleted.
    /// </summary>
    public static void DisposeData() {
      var dataLocal = Interlocked.Exchange(ref data, null);
      dataLocal?.Dispose();
    }
    #endregion


    #region Properties
    //      ----------

    /// <summary>
    /// Configuration parameters if data gets stored in .csv files
    /// </summary>
    public CsvConfig? CsvConfig { get; }

    /// <summary>
    /// Is all data initialised
    /// </summary>
    public bool IsInitialised { get; private set; }

    /// <summary>
    /// Directory of all DictionaryChildren
    /// </summary>
    public StorageDictionary<DictionaryChild, DC> DictionaryChildren { get; private set; }

    /// <summary>
    /// Directory of all LookupChildren
    /// </summary>
    public StorageDictionary<LookupChild, DC> LookupChildren { get; private set; }

    /// <summary>
    /// Directory of all LookupParents
    /// </summary>
    public StorageDictionary<LookupParent, DC> LookupParents { get; private set; }

    /// <summary>
    /// Directory of all LookupParentNullables
    /// </summary>
    public StorageDictionary<LookupParentNullable, DC> LookupParentNullables { get; private set; }

    /// <summary>
    /// Directory of all ParentsWithDictionary
    /// </summary>
    public StorageDictionary<ParentWithDictionary, DC> ParentsWithDictionary { get; private set; }

    /// <summary>
    /// Directory of all ParentsWithDictionaryNullable
    /// </summary>
    public StorageDictionary<ParentWithDictionaryNullable, DC> ParentsWithDictionaryNullable { get; private set; }

    /// <summary>
    /// Directory of all ParentsWithSortedList
    /// </summary>
    public StorageDictionary<ParentWithSortedList, DC> ParentsWithSortedList { get; private set; }

    /// <summary>
    /// Directory of all ParentsWithSortedListNullable
    /// </summary>
    public StorageDictionary<ParentWithSortedListNullable, DC> ParentsWithSortedListNullable { get; private set; }

    /// <summary>
    /// Directory of all PrivateConstructors
    /// </summary>
    public StorageDictionary<PrivateConstructor, DC> PrivateConstructors { get; private set; }

    /// <summary>
    /// Directory of all ReadOnlyChildren
    /// </summary>
    public StorageDictionary<ReadOnlyChild, DC> ReadOnlyChildren { get; private set; }

    /// <summary>
    /// Directory of all ReadOnlyParents
    /// </summary>
    public StorageDictionary<ReadOnlyParent, DC> ReadOnlyParents { get; private set; }

    /// <summary>
    /// Directory of all ReadOnlyParent2s
    /// </summary>
    public StorageDictionary<ReadOnlyParent2, DC> ReadOnlyParent2s { get; private set; }

    /// <summary>
    /// Directory of all ReadOnlyParent2Nullables
    /// </summary>
    public StorageDictionary<ReadOnlyParent2Nullable, DC> ReadOnlyParent2Nullables { get; private set; }

    /// <summary>
    /// Directory of all ReadOnlyParentNullables
    /// </summary>
    public StorageDictionary<ReadOnlyParentNullable, DC> ReadOnlyParentNullables { get; private set; }

    /// <summary>
    /// Directory of all SampleX
    /// </summary>
    public StorageDictionary<Sample, DC> SampleX { get; private set; }

    /// <summary>
    /// Directory of all SampleDetails
    /// </summary>
    public StorageDictionary<SampleDetail, DC> SampleDetails { get; private set; }

    /// <summary>
    /// Directory of all SampleMasters
    /// </summary>
    public StorageDictionary<SampleMaster, DC> SampleMasters { get; private set; }

    /// <summary>
    /// Directory of all SortedListChildren
    /// </summary>
    public StorageDictionary<SortedListChild, DC> SortedListChildren { get; private set; }

    /// <summary>
    /// Directory of all UpdatableChildren
    /// </summary>
    public StorageDictionary<UpdatableChild, DC> UpdatableChildren { get; private set; }
    #endregion


    #region Events
    //      ------

    #endregion


    #region Constructors
    //      ------------

    /// <summary>
    /// Creates a new data context. If csvConfig is null, the data is only stored in RAM, but gets lost once 
    /// program terminates. With csvConfig defined, existing data gets read at startup, changes immediately
    /// when written and Dispose() ensures by flushing that all data is permanently stored.
    /// </summary>
    public DC(CsvConfig? csvConfig) {
      if (!IsDisposed) {
        throw new Exception("Dispose old DC before creating a new one.");
      }
      isDisposed = 0;
      data = this;
      IsInitialised = false;

      onConstruct();

      CsvConfig = csvConfig;
      if (csvConfig==null) {
        SampleMasters = new StorageDictionary<SampleMaster, DC>(
          this,
          SampleMaster.SetKey,
          null,
          areInstancesUpdatable: true,
          areInstancesDeletable: false);
        SampleX = new StorageDictionary<Sample, DC>(
          this,
          Sample.SetKey,
          Sample.Disconnect,
          areInstancesUpdatable: true,
          areInstancesDeletable: true);
        SampleDetails = new StorageDictionary<SampleDetail, DC>(
          this,
          SampleDetail.SetKey,
          SampleDetail.Disconnect,
          areInstancesUpdatable: true,
          areInstancesDeletable: true);
        LookupParents = new StorageDictionary<LookupParent, DC>(
          this,
          LookupParent.SetKey,
          null,
          areInstancesUpdatable: false,
          areInstancesDeletable: false);
        LookupParentNullables = new StorageDictionary<LookupParentNullable, DC>(
          this,
          LookupParentNullable.SetKey,
          null,
          areInstancesUpdatable: false,
          areInstancesDeletable: true);
        LookupChildren = new StorageDictionary<LookupChild, DC>(
          this,
          LookupChild.SetKey,
          null,
          areInstancesUpdatable: false,
          areInstancesDeletable: false);
        ParentsWithDictionary = new StorageDictionary<ParentWithDictionary, DC>(
          this,
          ParentWithDictionary.SetKey,
          ParentWithDictionary.Disconnect,
          areInstancesUpdatable: true,
          areInstancesDeletable: true);
        ParentsWithDictionaryNullable = new StorageDictionary<ParentWithDictionaryNullable, DC>(
          this,
          ParentWithDictionaryNullable.SetKey,
          ParentWithDictionaryNullable.Disconnect,
          areInstancesUpdatable: true,
          areInstancesDeletable: true);
        DictionaryChildren = new StorageDictionary<DictionaryChild, DC>(
          this,
          DictionaryChild.SetKey,
          DictionaryChild.Disconnect,
          areInstancesUpdatable: true,
          areInstancesDeletable: true);
        ParentsWithSortedList = new StorageDictionary<ParentWithSortedList, DC>(
          this,
          ParentWithSortedList.SetKey,
          ParentWithSortedList.Disconnect,
          areInstancesUpdatable: true,
          areInstancesDeletable: true);
        ParentsWithSortedListNullable = new StorageDictionary<ParentWithSortedListNullable, DC>(
          this,
          ParentWithSortedListNullable.SetKey,
          ParentWithSortedListNullable.Disconnect,
          areInstancesUpdatable: true,
          areInstancesDeletable: true);
        SortedListChildren = new StorageDictionary<SortedListChild, DC>(
          this,
          SortedListChild.SetKey,
          SortedListChild.Disconnect,
          areInstancesUpdatable: true,
          areInstancesDeletable: true);
        ReadOnlyParents = new StorageDictionary<ReadOnlyParent, DC>(
          this,
          ReadOnlyParent.SetKey,
          null,
          areInstancesUpdatable: false,
          areInstancesDeletable: false);
        ReadOnlyParentNullables = new StorageDictionary<ReadOnlyParentNullable, DC>(
          this,
          ReadOnlyParentNullable.SetKey,
          null,
          areInstancesUpdatable: false,
          areInstancesDeletable: false);
        ReadOnlyChildren = new StorageDictionary<ReadOnlyChild, DC>(
          this,
          ReadOnlyChild.SetKey,
          null,
          areInstancesUpdatable: false,
          areInstancesDeletable: false);
        ReadOnlyParent2s = new StorageDictionary<ReadOnlyParent2, DC>(
          this,
          ReadOnlyParent2.SetKey,
          null,
          areInstancesUpdatable: false,
          areInstancesDeletable: false);
        ReadOnlyParent2Nullables = new StorageDictionary<ReadOnlyParent2Nullable, DC>(
          this,
          ReadOnlyParent2Nullable.SetKey,
          null,
          areInstancesUpdatable: false,
          areInstancesDeletable: false);
        UpdatableChildren = new StorageDictionary<UpdatableChild, DC>(
          this,
          UpdatableChild.SetKey,
          null,
          areInstancesUpdatable: true,
          areInstancesDeletable: false);
        PrivateConstructors = new StorageDictionary<PrivateConstructor, DC>(
          this,
          PrivateConstructor.SetKey,
          null,
          areInstancesUpdatable: true,
          areInstancesDeletable: true);
      } else {
        SampleMasters = new StorageDictionaryCSV<SampleMaster, DC>(
          this,
          csvConfig!,
          SampleMaster.MaxLineLength,
          SampleMaster.Headers,
          SampleMaster.SetKey,
          SampleMaster.Create,
          null,
          SampleMaster.Update,
          SampleMaster.Write,
          null,
          areInstancesUpdatable: true,
          areInstancesDeletable: false);
        SampleX = new StorageDictionaryCSV<Sample, DC>(
          this,
          csvConfig!,
          Sample.MaxLineLength,
          Sample.Headers,
          Sample.SetKey,
          Sample.Create,
          Sample.Verify,
          Sample.Update,
          Sample.Write,
          Sample.Disconnect,
          areInstancesUpdatable: true,
          areInstancesDeletable: true);
        SampleDetails = new StorageDictionaryCSV<SampleDetail, DC>(
          this,
          csvConfig!,
          SampleDetail.MaxLineLength,
          SampleDetail.Headers,
          SampleDetail.SetKey,
          SampleDetail.Create,
          SampleDetail.Verify,
          SampleDetail.Update,
          SampleDetail.Write,
          SampleDetail.Disconnect,
          areInstancesUpdatable: true,
          areInstancesDeletable: true);
        LookupParents = new StorageDictionaryCSV<LookupParent, DC>(
          this,
          csvConfig!,
          LookupParent.MaxLineLength,
          LookupParent.Headers,
          LookupParent.SetKey,
          LookupParent.Create,
          null,
          null,
          LookupParent.Write,
          null,
          areInstancesUpdatable: false,
          areInstancesDeletable: false);
        LookupParentNullables = new StorageDictionaryCSV<LookupParentNullable, DC>(
          this,
          csvConfig!,
          LookupParentNullable.MaxLineLength,
          LookupParentNullable.Headers,
          LookupParentNullable.SetKey,
          LookupParentNullable.Create,
          null,
          null,
          LookupParentNullable.Write,
          null,
          areInstancesUpdatable: false,
          areInstancesDeletable: true);
        LookupChildren = new StorageDictionaryCSV<LookupChild, DC>(
          this,
          csvConfig!,
          LookupChild.MaxLineLength,
          LookupChild.Headers,
          LookupChild.SetKey,
          LookupChild.Create,
          null,
          null,
          LookupChild.Write,
          null,
          areInstancesUpdatable: false,
          areInstancesDeletable: false);
        ParentsWithDictionary = new StorageDictionaryCSV<ParentWithDictionary, DC>(
          this,
          csvConfig!,
          ParentWithDictionary.MaxLineLength,
          ParentWithDictionary.Headers,
          ParentWithDictionary.SetKey,
          ParentWithDictionary.Create,
          null,
          ParentWithDictionary.Update,
          ParentWithDictionary.Write,
          ParentWithDictionary.Disconnect,
          areInstancesUpdatable: true,
          areInstancesDeletable: true);
        ParentsWithDictionaryNullable = new StorageDictionaryCSV<ParentWithDictionaryNullable, DC>(
          this,
          csvConfig!,
          ParentWithDictionaryNullable.MaxLineLength,
          ParentWithDictionaryNullable.Headers,
          ParentWithDictionaryNullable.SetKey,
          ParentWithDictionaryNullable.Create,
          null,
          ParentWithDictionaryNullable.Update,
          ParentWithDictionaryNullable.Write,
          ParentWithDictionaryNullable.Disconnect,
          areInstancesUpdatable: true,
          areInstancesDeletable: true);
        DictionaryChildren = new StorageDictionaryCSV<DictionaryChild, DC>(
          this,
          csvConfig!,
          DictionaryChild.MaxLineLength,
          DictionaryChild.Headers,
          DictionaryChild.SetKey,
          DictionaryChild.Create,
          DictionaryChild.Verify,
          DictionaryChild.Update,
          DictionaryChild.Write,
          DictionaryChild.Disconnect,
          areInstancesUpdatable: true,
          areInstancesDeletable: true);
        ParentsWithSortedList = new StorageDictionaryCSV<ParentWithSortedList, DC>(
          this,
          csvConfig!,
          ParentWithSortedList.MaxLineLength,
          ParentWithSortedList.Headers,
          ParentWithSortedList.SetKey,
          ParentWithSortedList.Create,
          null,
          ParentWithSortedList.Update,
          ParentWithSortedList.Write,
          ParentWithSortedList.Disconnect,
          areInstancesUpdatable: true,
          areInstancesDeletable: true);
        ParentsWithSortedListNullable = new StorageDictionaryCSV<ParentWithSortedListNullable, DC>(
          this,
          csvConfig!,
          ParentWithSortedListNullable.MaxLineLength,
          ParentWithSortedListNullable.Headers,
          ParentWithSortedListNullable.SetKey,
          ParentWithSortedListNullable.Create,
          null,
          ParentWithSortedListNullable.Update,
          ParentWithSortedListNullable.Write,
          ParentWithSortedListNullable.Disconnect,
          areInstancesUpdatable: true,
          areInstancesDeletable: true);
        SortedListChildren = new StorageDictionaryCSV<SortedListChild, DC>(
          this,
          csvConfig!,
          SortedListChild.MaxLineLength,
          SortedListChild.Headers,
          SortedListChild.SetKey,
          SortedListChild.Create,
          SortedListChild.Verify,
          SortedListChild.Update,
          SortedListChild.Write,
          SortedListChild.Disconnect,
          areInstancesUpdatable: true,
          areInstancesDeletable: true);
        ReadOnlyParents = new StorageDictionaryCSV<ReadOnlyParent, DC>(
          this,
          csvConfig!,
          ReadOnlyParent.MaxLineLength,
          ReadOnlyParent.Headers,
          ReadOnlyParent.SetKey,
          ReadOnlyParent.Create,
          null,
          null,
          ReadOnlyParent.Write,
          null,
          areInstancesUpdatable: false,
          areInstancesDeletable: false);
        ReadOnlyParentNullables = new StorageDictionaryCSV<ReadOnlyParentNullable, DC>(
          this,
          csvConfig!,
          ReadOnlyParentNullable.MaxLineLength,
          ReadOnlyParentNullable.Headers,
          ReadOnlyParentNullable.SetKey,
          ReadOnlyParentNullable.Create,
          null,
          null,
          ReadOnlyParentNullable.Write,
          null,
          areInstancesUpdatable: false,
          areInstancesDeletable: false);
        ReadOnlyChildren = new StorageDictionaryCSV<ReadOnlyChild, DC>(
          this,
          csvConfig!,
          ReadOnlyChild.MaxLineLength,
          ReadOnlyChild.Headers,
          ReadOnlyChild.SetKey,
          ReadOnlyChild.Create,
          ReadOnlyChild.Verify,
          null,
          ReadOnlyChild.Write,
          null,
          areInstancesUpdatable: false,
          areInstancesDeletable: false);
        ReadOnlyParent2s = new StorageDictionaryCSV<ReadOnlyParent2, DC>(
          this,
          csvConfig!,
          ReadOnlyParent2.MaxLineLength,
          ReadOnlyParent2.Headers,
          ReadOnlyParent2.SetKey,
          ReadOnlyParent2.Create,
          null,
          null,
          ReadOnlyParent2.Write,
          null,
          areInstancesUpdatable: false,
          areInstancesDeletable: false);
        ReadOnlyParent2Nullables = new StorageDictionaryCSV<ReadOnlyParent2Nullable, DC>(
          this,
          csvConfig!,
          ReadOnlyParent2Nullable.MaxLineLength,
          ReadOnlyParent2Nullable.Headers,
          ReadOnlyParent2Nullable.SetKey,
          ReadOnlyParent2Nullable.Create,
          null,
          null,
          ReadOnlyParent2Nullable.Write,
          null,
          areInstancesUpdatable: false,
          areInstancesDeletable: false);
        UpdatableChildren = new StorageDictionaryCSV<UpdatableChild, DC>(
          this,
          csvConfig!,
          UpdatableChild.MaxLineLength,
          UpdatableChild.Headers,
          UpdatableChild.SetKey,
          UpdatableChild.Create,
          UpdatableChild.Verify,
          UpdatableChild.Update,
          UpdatableChild.Write,
          null,
          areInstancesUpdatable: true,
          areInstancesDeletable: false);
        PrivateConstructors = new StorageDictionaryCSV<PrivateConstructor, DC>(
          this,
          csvConfig!,
          PrivateConstructor.MaxLineLength,
          PrivateConstructor.Headers,
          PrivateConstructor.SetKey,
          PrivateConstructor.Create,
          null,
          PrivateConstructor.Update,
          PrivateConstructor.Write,
          null,
          areInstancesUpdatable: true,
          areInstancesDeletable: true);
      }
      onConstructed();
      IsInitialised = true;
    }

    /// <summary>}
    /// Called at beginning of constructor
    /// </summary>}
    partial void onConstruct();

    /// <summary>}
    /// Called at end of constructor
    /// </summary>}
    partial void onConstructed();
    #endregion


    #region IDisposable Support
    //      -------------------

    /// <summary>
    /// Is DC.Data already disposed ?
    /// </summary>
    public bool IsDisposed {
      get { return isDisposed==1; }
    }
    int isDisposed = 1;


    protected virtual void Dispose(bool disposing) {
      var wasDisposed = Interlocked.Exchange(ref isDisposed, 1);//prevents that 2 threads dispose simultaneously
      if (wasDisposed==1) return; // already disposed

      if (disposing) {
        onDispose();
        PrivateConstructors.Dispose();
        UpdatableChildren.Dispose();
        ReadOnlyParent2Nullables.Dispose();
        ReadOnlyParent2s.Dispose();
        ReadOnlyChildren.Dispose();
        ReadOnlyParentNullables.Dispose();
        ReadOnlyParents.Dispose();
        SortedListChildren.Dispose();
        ParentsWithSortedListNullable.Dispose();
        ParentsWithSortedList.Dispose();
        DictionaryChildren.Dispose();
        ParentsWithDictionaryNullable.Dispose();
        ParentsWithDictionary.Dispose();
        LookupChildren.Dispose();
        LookupParentNullables.Dispose();
        LookupParents.Dispose();
        SampleDetails.Dispose();
        SampleX.Dispose();
        SampleMasters.Dispose();
        data = null;
      }
    }

    /// <summary>}
    /// Called before storageDirectories get disposed.
    /// </summary>}
    partial void onDispose();


    public void Dispose() {
      Dispose(true);
    }
    #endregion


    #region Methods
    //      -------

    #endregion

  }
}

