//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by StorageClassGenerator
//
//     Do not change code in this file, it will get lost when the file gets 
//     auto generated again. Write your code into Lookup_ParentNullable.cs.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using Storage;


namespace StorageModel  {


    /// <summary>
    /// Parent of children who use lookup, i.e. parent has no children collection,  where the child's 
    /// parent property is nullable.
    /// </summary>
  public partial class Lookup_ParentNullable: IStorage<Lookup_ParentNullable> {

    #region Properties
    //      ----------

    /// <summary>
    /// Unique identifier for Lookup_ParentNullable. Gets set once Lookup_ParentNullable gets added to DC.Data.
    /// </summary>
    public int Key { get; private set; }
    internal static void SetKey(Lookup_ParentNullable lookup_ParentNullable, int key) { lookup_ParentNullable.Key = key; }


    /// <summary>
    /// Stores only dates but no times.
    ///  </summary>
    public DateTime Date { get; }


    /// <summary>
    /// Stores decimal with 2 digits after comma.
    ///  </summary>
    public decimal SomeValue { get; }


    /// <summary>
    /// Headers written to first line in CSV file
    /// </summary>
    internal static readonly string[] Headers = {"Key", "Date", "SomeValue"};


    /// <summary>
    /// None existing Lookup_ParentNullable
    /// </summary>
    internal static Lookup_ParentNullable NoLookup_ParentNullable = new Lookup_ParentNullable(DateTime.MinValue.Date, Decimal.MinValue, isStoring: false);
    #endregion


    #region Events
    //      ------

    /// <summary>
    /// This event will never be raised, but is needed to comply with IStorage.
    /// </summary>
#pragma warning disable 67
    public event Action<Lookup_ParentNullable>? HasChanged;
#pragma warning restore 67
    #endregion


    #region Constructors
    //      ------------

    /// <summary>
    /// Lookup_ParentNullable Constructor. If isStoring is true, adds Lookup_ParentNullable to DC.Data.Lookup_ParentNullables.
    /// </summary>
    public Lookup_ParentNullable(DateTime date, decimal someValue, bool isStoring = true) {
      Key = StorageExtensions.NoKey;
      Date = date.Floor(Rounding.Days);
      SomeValue = someValue.Round(2);
      onConstruct();

      if (isStoring) {
        Store();
      }
    }
    partial void onConstruct();


    /// <summary>
    /// Constructor for Lookup_ParentNullable read from CSV file
    /// </summary>
    private Lookup_ParentNullable(int key, CsvReader csvReader, DC context) {
      Key = key;
      Date = csvReader.ReadDate();
      SomeValue = csvReader.ReadDecimal();
      onCsvConstruct(context);
    }
    partial void onCsvConstruct(DC context);


    /// <summary>
    /// New Lookup_ParentNullable read from CSV file
    /// </summary>
    internal static Lookup_ParentNullable Create(int key, CsvReader csvReader, DC context) {
      return new Lookup_ParentNullable(key, csvReader, context);
    }
    #endregion


    #region Methods
    //      -------

    /// <summary>
    /// Adds Lookup_ParentNullable to DC.Data.Lookup_ParentNullables. 
    /// </summary>
    public void Store() {
      if (Key>=0) {
        throw new Exception($"Lookup_ParentNullable cannot be stored again in DC.Data, key is {Key} greater equal 0." + Environment.NewLine + ToString());
      }
      var isCancelled = false;
      onStoring(ref isCancelled);
      if (isCancelled) return;

      DC.Data.Lookup_ParentNullables.Add(this);
      onStored();
    }
    partial void onStoring(ref bool isCancelled);
    partial void onStored();


    /// <summary>
    /// Estimated number of UTF8 characters needed to write Lookup_ParentNullable to CSV file
    /// </summary>
    public const int EstimatedLineLength = 23;


    /// <summary>
    /// Write Lookup_ParentNullable to CSV file
    /// </summary>
    internal static void Write(Lookup_ParentNullable lookup_ParentNullable, CsvWriter csvWriter) {
      lookup_ParentNullable.onCsvWrite();
      csvWriter.WriteDate(lookup_ParentNullable.Date);
      csvWriter.WriteDecimal2(lookup_ParentNullable.SomeValue);
    }
    partial void onCsvWrite();


    /// <summary>
    /// Removes Lookup_ParentNullable from DC.Data.Lookup_ParentNullables.
    /// </summary>
    public void Remove() {
      if (Key<0) {
        throw new Exception($"Lookup_ParentNullable.Remove(): Lookup_ParentNullable 'Class Lookup_ParentNullable' is not stored in DC.Data, key is {Key}.");
      }
      onRemove();
      DC.Data.Lookup_ParentNullables.Remove(Key);
    }
    partial void onRemove();


    /// <summary>
    /// Returns property values
    /// </summary>
    public string ToShortString() {
      var returnString =
        $"{Key.ToKeyString()}," +
        $" {Date.ToShortDateString()}," +
        $" {SomeValue}";
      onToShortString(ref returnString);
      return returnString;
    }
    partial void onToShortString(ref string returnString);


    /// <summary>
    /// Returns all property names and values
    /// </summary>
    public override string ToString() {
      var returnString =
        $"Key: {Key}," +
        $" Date: {Date.ToShortDateString()}," +
        $" SomeValue: {SomeValue};";
      onToString(ref returnString);
      return returnString;
    }
    partial void onToString(ref string returnString);
    #endregion
  }
}
