//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by StorageClassGenerator
//
//     Do not change code in this file, it will get lost when the file gets 
//     auto generated again. Write your code into PropertyNeedsDictionaryClass.cs.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using Storage;


namespace StorageModel  {


    ///// <summary>
    ///// Readonly Child class with one parent property which is not nullable and one property to a different parent 
    ///// which is nullable
    ///// </summary>
    //  /// <summary>
    //  /// Some Text comment
    //  /// </summary>
    //  /// <summary>
    //  /// Links to parent
    //  /// </summary>
    //  /// <summary>
    //  /// Links to parent conditionally
    //  /// </summary>
    /// <summary>
    /// Some comment for PropertyNeedsDictionaryClass
    /// </summary>
  public partial class PropertyNeedsDictionaryClass: IStorage<PropertyNeedsDictionaryClass> {

    #region Properties
    //      ----------

    /// <summary>
    /// Unique identifier for PropertyNeedsDictionaryClass. Gets set once PropertyNeedsDictionaryClass gets added to DC.Data.
    /// </summary>
    public int Key { get; private set; }
    internal static void SetKey(PropertyNeedsDictionaryClass propertyNeedsDictionaryClass, int key) { propertyNeedsDictionaryClass.Key = key; }


    /// <summary>
    /// Used as key into dictionary SampleWithDictionaryByIdInt
    /// </summary>
    public int IdInt { get; private set; }


    /// <summary>
    /// Used as key into dictionary SampleWithDictionaryByIdString
    /// </summary>
    public string? IdString { get; private set; }


    /// <summary>
    /// Some Text comment
    /// </summary>
    public string Text { get; private set; }


    /// <summary>
    /// Headers written to first line in CSV file
    /// </summary>
    internal static readonly string[] Headers = {"Key", "IdInt", "IdString", "Text"};


    /// <summary>
    /// None existing PropertyNeedsDictionaryClass
    /// </summary>
    internal static PropertyNeedsDictionaryClass NoPropertyNeedsDictionaryClass = new PropertyNeedsDictionaryClass(int.MinValue, null, "NoText", isStoring: false);
    #endregion


    #region Events
    //      ------

    /// <summary>
    /// Content of PropertyNeedsDictionaryClass has changed. Gets only raised for changes occurring after loading DC.Data with previously stored data.
    /// </summary>
    public event Action<PropertyNeedsDictionaryClass>? HasChanged;
    #endregion


    #region Constructors
    //      ------------

    /// <summary>
    /// PropertyNeedsDictionaryClass Constructor. If isStoring is true, adds PropertyNeedsDictionaryClass to DC.Data.PropertyNeedsDictionaryClasses.
    /// </summary>
    public PropertyNeedsDictionaryClass(int idInt, string? idString, string text, bool isStoring = true) {
      Key = StorageExtensions.NoKey;
      IdInt = idInt;
      IdString = idString;
      Text = text;
      onConstruct();

      if (isStoring) {
        Store();
      }
    }
    partial void onConstruct();


    /// <summary>
    /// Constructor for PropertyNeedsDictionaryClass read from CSV file
    /// </summary>
    private PropertyNeedsDictionaryClass(int key, CsvReader csvReader, DC context) {
      Key = key;
      IdInt = csvReader.ReadInt();
      DC.Data.PropertyNeedsDictionaryClassesByIdInt.Add(IdInt, this);
      IdString = csvReader.ReadStringNull();
      if (IdString!=null) {
        DC.Data.PropertyNeedsDictionaryClassesByIdString.Add(IdString, this);
      }
      Text = csvReader.ReadString();
      onCsvConstruct(context);
    }
    partial void onCsvConstruct(DC context);


    /// <summary>
    /// New PropertyNeedsDictionaryClass read from CSV file
    /// </summary>
    internal static PropertyNeedsDictionaryClass Create(int key, CsvReader csvReader, DC context) {
      return new PropertyNeedsDictionaryClass(key, csvReader, context);
    }
    #endregion


    #region Methods
    //      -------

    /// <summary>
    /// Adds PropertyNeedsDictionaryClass to DC.Data.PropertyNeedsDictionaryClasses. 
    /// </summary>
    public void Store() {
      if (Key>=0) {
        throw new Exception($"PropertyNeedsDictionaryClass cannot be stored again in DC.Data, key is {Key} greater equal 0." + Environment.NewLine + ToString());
      }
      var isCancelled = false;
      onStoring(ref isCancelled);
      if (isCancelled) return;

      DC.Data.PropertyNeedsDictionaryClasses.Add(this);
      DC.Data.PropertyNeedsDictionaryClassesByIdInt.Add(IdInt, this);
      if (IdString!=null) {
        DC.Data.PropertyNeedsDictionaryClassesByIdString.Add(IdString, this);
      }
      onStored();
    }
    partial void onStoring(ref bool isCancelled);
    partial void onStored();


    /// <summary>
    /// Maximal number of UTF8 characters needed to write PropertyNeedsDictionaryClass to CSV file
    /// </summary>
    public const int MaxLineLength = 311;


    /// <summary>
    /// Write PropertyNeedsDictionaryClass to CSV file
    /// </summary>
    internal static void Write(PropertyNeedsDictionaryClass propertyNeedsDictionaryClass, CsvWriter csvWriter) {
      propertyNeedsDictionaryClass.onCsvWrite();
      csvWriter.Write(propertyNeedsDictionaryClass.IdInt);
      csvWriter.Write(propertyNeedsDictionaryClass.IdString);
      csvWriter.Write(propertyNeedsDictionaryClass.Text);
    }
    partial void onCsvWrite();


    /// <summary>
    /// Updates PropertyNeedsDictionaryClass with the provided values
    /// </summary>
    public void Update(int idInt, string? idString, string text) {
      var isCancelled = false;
      onUpdating(idInt, idString, text, ref isCancelled);
      if (isCancelled) return;

      var isChangeDetected = false;
      if (IdInt!=idInt) {
        DC.Data.PropertyNeedsDictionaryClassesByIdInt.Remove(IdInt);
        IdInt = idInt;
        DC.Data.PropertyNeedsDictionaryClassesByIdInt.Add(IdInt, this);
        isChangeDetected = true;
      }
      if (IdString!=idString) {
        if (IdString!=null) {
          DC.Data.PropertyNeedsDictionaryClassesByIdString.Remove(IdString);
        }
        IdString = idString;
        if (IdString!=null) {
          DC.Data.PropertyNeedsDictionaryClassesByIdString.Add(IdString, this);
        }
        isChangeDetected = true;
      }
      if (Text!=text) {
        Text = text;
        isChangeDetected = true;
      }
      if (isChangeDetected) {
        onUpdated();
        HasChanged?.Invoke(this);
      }
    }
    partial void onUpdating(int idInt, string? idString, string text, ref bool isCancelled);
    partial void onUpdated();


    /// <summary>
    /// Updates this PropertyNeedsDictionaryClass with values from CSV file
    /// </summary>
    internal static void Update(PropertyNeedsDictionaryClass propertyNeedsDictionaryClass, CsvReader csvReader, DC _) {
      DC.Data.PropertyNeedsDictionaryClassesByIdInt.Remove(propertyNeedsDictionaryClass.IdInt);
      propertyNeedsDictionaryClass.IdInt = csvReader.ReadInt();
      DC.Data.PropertyNeedsDictionaryClassesByIdInt.Add(propertyNeedsDictionaryClass.IdInt, propertyNeedsDictionaryClass);
      if (propertyNeedsDictionaryClass.IdString!=null) {
        DC.Data.PropertyNeedsDictionaryClassesByIdString.Remove(propertyNeedsDictionaryClass.IdString);
      }
      propertyNeedsDictionaryClass.IdString = csvReader.ReadStringNull();
      if (propertyNeedsDictionaryClass.IdString!=null) {
        DC.Data.PropertyNeedsDictionaryClassesByIdString.Add(propertyNeedsDictionaryClass.IdString, propertyNeedsDictionaryClass);
      }
      propertyNeedsDictionaryClass.Text = csvReader.ReadString();
      propertyNeedsDictionaryClass.onCsvUpdate();
    }
    partial void onCsvUpdate();


    /// <summary>
    /// Removes PropertyNeedsDictionaryClass from DC.Data.PropertyNeedsDictionaryClasses, 
    /// removes PropertyNeedsDictionaryClass from DC.Data.PropertyNeedsDictionaryClassesByIdInt and 
    /// removes PropertyNeedsDictionaryClass from DC.Data.PropertyNeedsDictionaryClassesByIdString.
    /// </summary>
    public void Remove() {
      if (Key<0) {
        throw new Exception($"PropertyNeedsDictionaryClass.Remove(): PropertyNeedsDictionaryClass 'Class PropertyNeedsDictionaryClass' is not stored in DC.Data, key is {Key}.");
      }
      onRemove();
      DC.Data.PropertyNeedsDictionaryClasses.Remove(Key);
    }
    partial void onRemove();


    /// <summary>
    /// Removes PropertyNeedsDictionaryClass from DC.Data.PropertyNeedsDictionaryClassesByIdInt and 
    /// removes PropertyNeedsDictionaryClass from DC.Data.PropertyNeedsDictionaryClassesByIdString.
    /// </summary>
    internal static void Disconnect(PropertyNeedsDictionaryClass propertyNeedsDictionaryClass) {
      DC.Data.PropertyNeedsDictionaryClassesByIdInt.Remove(propertyNeedsDictionaryClass.IdInt);
      if (propertyNeedsDictionaryClass.IdString!=null) {
        DC.Data.PropertyNeedsDictionaryClassesByIdString.Remove(propertyNeedsDictionaryClass.IdString);
      }
    }


    /// <summary>
    /// Returns property values
    /// </summary>
    public string ToShortString() {
      var returnString =
        $"{Key.ToKeyString()}," +
        $" {IdInt}," +
        $" {IdString}," +
        $" {Text}";
      onToShortString(ref returnString);
      return returnString;
    }
    partial void onToShortString(ref string returnString);


    /// <summary>
    /// Returns all property names and values
    /// </summary>
    public override string ToString() {
      var returnString =
        $"Key: {Key}," +
        $" IdInt: {IdInt}," +
        $" IdString: {IdString}," +
        $" Text: {Text};";
      onToString(ref returnString);
      return returnString;
    }
    partial void onToString(ref string returnString);
    #endregion
  }
}
