//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by StorageClassGenerator
//
//     Do not change code in this file, it will get lost when the file gets 
//     auto generated again. Write your code into ReadOnlyParentUpdatableChild_Parent.cs.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using Storage;


namespace StorageModel  {


    /// <summary>
    /// Example of a "readonly" Parent, i.e. the parent's properties will not change and the parent will never get
    /// deleted, but it is still possible to add children, but not to remove them.
    /// </summary>
  public partial class ReadOnlyParentUpdatableChild_Parent: IStorage<ReadOnlyParentUpdatableChild_Parent> {

    #region Properties
    //      ----------

    /// <summary>
    /// Unique identifier for ReadOnlyParentUpdatableChild_Parent. Gets set once ReadOnlyParentUpdatableChild_Parent gets added to DC.Data.
    /// </summary>
    public int Key { get; private set; }
    internal static void SetKey(ReadOnlyParentUpdatableChild_Parent readOnlyParentUpdatableChild_Parent, int key) { readOnlyParentUpdatableChild_Parent.Key = key; }


    /// <summary>
    /// Readonly Text, because class is not updatable
    /// </summary>
    public string Text { get; }


    /// <summary>
    /// List of children
    /// </summary>
    public IReadOnlyList<ReadOnlyParentUpdatableChild_Child> ReadOnlyParentUpdatableChild_Children => readOnlyParentUpdatableChild_Children;
    readonly List<ReadOnlyParentUpdatableChild_Child> readOnlyParentUpdatableChild_Children;


    /// <summary>
    /// Headers written to first line in CSV file
    /// </summary>
    internal static readonly string[] Headers = {"Text"};


    /// <summary>
    /// None existing ReadOnlyParentUpdatableChild_Parent
    /// </summary>
    internal static ReadOnlyParentUpdatableChild_Parent NoReadOnlyParentUpdatableChild_Parent = new ReadOnlyParentUpdatableChild_Parent("NoText", isStoring: false);
    #endregion


    #region Events
    //      ------

    /// <summary>
    /// This event will never be raised, but is needed to comply with IStorage.
    /// </summary>
#pragma warning disable 67
    public event Action<ReadOnlyParentUpdatableChild_Parent>? HasChanged;
#pragma warning restore 67
    #endregion


    #region Constructors
    //      ------------

    /// <summary>
    /// ReadOnlyParentUpdatableChild_Parent Constructor. If isStoring is true, adds ReadOnlyParentUpdatableChild_Parent to DC.Data.ReadOnlyParentUpdatableChild_Parents.
    /// </summary>
    public ReadOnlyParentUpdatableChild_Parent(string text, bool isStoring = true) {
      Key = StorageExtensions.NoKey;
      Text = text;
      readOnlyParentUpdatableChild_Children = new List<ReadOnlyParentUpdatableChild_Child>();
      onConstruct();

      if (isStoring) {
        Store();
      }
    }
    partial void onConstruct();


    /// <summary>
    /// Constructor for ReadOnlyParentUpdatableChild_Parent read from CSV file
    /// </summary>
    private ReadOnlyParentUpdatableChild_Parent(int key, CsvReader csvReader, DC context) {
      Key = key;
      Text = csvReader.ReadString();
      readOnlyParentUpdatableChild_Children = new List<ReadOnlyParentUpdatableChild_Child>();
      onCsvConstruct(context);
    }
    partial void onCsvConstruct(DC context);


    /// <summary>
    /// New ReadOnlyParentUpdatableChild_Parent read from CSV file
    /// </summary>
    internal static ReadOnlyParentUpdatableChild_Parent Create(int key, CsvReader csvReader, DC context) {
      return new ReadOnlyParentUpdatableChild_Parent(key, csvReader, context);
    }
    #endregion


    #region Methods
    //      -------

    /// <summary>
    /// Adds ReadOnlyParentUpdatableChild_Parent to DC.Data.ReadOnlyParentUpdatableChild_Parents. 
    /// </summary>
    public void Store() {
      if (Key>=0) {
        throw new Exception($"ReadOnlyParentUpdatableChild_Parent cannot be stored again in DC.Data, key is {Key} greater equal 0." + Environment.NewLine + ToString());
      }
      onStore();
      DC.Data.ReadOnlyParentUpdatableChild_Parents.Add(this);
    }
    partial void onStore();


    /// <summary>
    /// Maximal number of UTF8 characters needed to write ReadOnlyParentUpdatableChild_Parent to CSV file
    /// </summary>
    public const int MaxLineLength = 150;


    /// <summary>
    /// Write ReadOnlyParentUpdatableChild_Parent to CSV file
    /// </summary>
    internal static void Write(ReadOnlyParentUpdatableChild_Parent readOnlyParentUpdatableChild_Parent, CsvWriter csvWriter) {
      readOnlyParentUpdatableChild_Parent.onCsvWrite();
      csvWriter.Write(readOnlyParentUpdatableChild_Parent.Text);
    }
    partial void onCsvWrite();


    /// <summary>
    /// Add readOnlyParentUpdatableChild_Child to ReadOnlyParentUpdatableChild_Children.
    /// </summary>
    internal void AddToReadOnlyParentUpdatableChild_Children(ReadOnlyParentUpdatableChild_Child readOnlyParentUpdatableChild_Child) {
      readOnlyParentUpdatableChild_Children.Add(readOnlyParentUpdatableChild_Child);
      onAddedToReadOnlyParentUpdatableChild_Children(readOnlyParentUpdatableChild_Child);
    }
    partial void onAddedToReadOnlyParentUpdatableChild_Children(ReadOnlyParentUpdatableChild_Child readOnlyParentUpdatableChild_Child);


    /// <summary>
    /// Removes readOnlyParentUpdatableChild_Child from ReadOnlyParentUpdatableChild_Parent.
    /// </summary>
    internal void RemoveFromReadOnlyParentUpdatableChild_Children(ReadOnlyParentUpdatableChild_Child readOnlyParentUpdatableChild_Child) {
#if DEBUG
      if (!readOnlyParentUpdatableChild_Children.Remove(readOnlyParentUpdatableChild_Child)) throw new Exception();
#else
        readOnlyParentUpdatableChild_Children.Remove(readOnlyParentUpdatableChild_Child);
#endif
      onRemovedFromReadOnlyParentUpdatableChild_Children(readOnlyParentUpdatableChild_Child);
    }
    partial void onRemovedFromReadOnlyParentUpdatableChild_Children(ReadOnlyParentUpdatableChild_Child readOnlyParentUpdatableChild_Child);


    /// <summary>
    /// Removing ReadOnlyParentUpdatableChild_Parent from DC.Data.ReadOnlyParentUpdatableChild_Parents is not supported.
    /// </summary>
    public void Remove() {
      throw new NotSupportedException("StorageClass attribute AreInstancesDeletable is false.");
    }


    /// <summary>
    /// Returns property values
    /// </summary>
    public string ToShortString() {
      var returnString =
        $"{Key.ToKeyString()}," +
        $" {Text}";
      onToShortString(ref returnString);
      return returnString;
    }
    partial void onToShortString(ref string returnString);


    /// <summary>
    /// Returns all property names and values
    /// </summary>
    public override string ToString() {
      var returnString =
        $"Key: {Key}," +
        $" Text: {Text}," +
        $" ReadOnlyParentUpdatableChild_Children: {ReadOnlyParentUpdatableChild_Children.Count};";
      onToString(ref returnString);
      return returnString;
    }
    partial void onToString(ref string returnString);
    #endregion
  }
}
