//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by StorageClassGenerator
//
//     Do not change code in this file, it will get lost when the file gets 
//     auto generated again. Write your code into SampleMaster.cs.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using Storage;


namespace StorageModel  {


    /// <summary>
    /// Some comment for SampleMaster.
    /// With an additional line.
    /// </summary>
  public partial class SampleMaster: IStorage<SampleMaster> {

    #region Properties
    //      ----------

    /// <summary>
    /// Unique identifier for SampleMaster. Gets set once SampleMaster gets added to DC.Data.
    /// </summary>
    public int Key { get; private set; }
    internal static void SetKey(SampleMaster sampleMaster, int key) { sampleMaster.Key = key; }


    /// <summary>
    /// Some Text comment
    /// </summary>
    public string Text { get; private set; }


    /// <summary>
    /// List representing parent child relationship
    /// </summary>
    public ICollection<Sample> SampleX => sampleX;
    readonly HashSet<Sample> sampleX;


    /// <summary>
    /// Integer property with int.MinValue as default
    /// </summary>
    public int NumberWithDefault { get; private set; }


    /// <summary>
    /// Headers written to first line in CSV file
    /// </summary>
    internal static readonly string[] Headers = {"Key", "Text", "NumberWithDefault"};


    /// <summary>
    /// None existing SampleMaster
    /// </summary>
    internal static SampleMaster NoSampleMaster = new SampleMaster("NoText", int.MinValue, isStoring: false);
    #endregion


    #region Events
    //      ------

    /// <summary>
    /// Content of SampleMaster has changed. Gets only raised for changes occurring after loading DC.Data with previously stored data.
    /// </summary>
    public event Action<SampleMaster>? HasChanged;
    #endregion


    #region Constructors
    //      ------------

    /// <summary>
    /// SampleMaster Constructor. If isStoring is true, adds SampleMaster to DC.Data.SampleMasters.
    /// </summary>
    public SampleMaster(string text, int numberWithDefault = int.MinValue, bool isStoring = true) {
      Key = StorageExtensions.NoKey;
      Text = text;
      sampleX = new HashSet<Sample>();
      NumberWithDefault = numberWithDefault;
      onConstruct();

      if (isStoring) {
        Store();
      }
    }
    partial void onConstruct();


    /// <summary>
    /// Constructor for SampleMaster read from CSV file
    /// </summary>
    private SampleMaster(int key, CsvReader csvReader, DC context) {
      Key = key;
      Text = csvReader.ReadString();
      sampleX = new HashSet<Sample>();
      NumberWithDefault = csvReader.ReadInt();
      onCsvConstruct(context);
    }
    partial void onCsvConstruct(DC context);


    /// <summary>
    /// New SampleMaster read from CSV file
    /// </summary>
    internal static SampleMaster Create(int key, CsvReader csvReader, DC context) {
      return new SampleMaster(key, csvReader, context);
    }
    #endregion


    #region Methods
    //      -------

    /// <summary>
    /// Adds SampleMaster to DC.Data.SampleMasters. 
    /// </summary>
    public void Store() {
      if (Key>=0) {
        throw new Exception($"SampleMaster can not be stored again in DC.Data, key is {Key} greater equal 0." + Environment.NewLine + ToString());
      }
      onStore();
      DC.Data.SampleMasters.Add(this);
    }
    partial void onStore();


    /// <summary>
    /// Maximal number of UTF8 characters needed to write SampleMaster to CSV file
    /// </summary>
    public const int MaxLineLength = 161;


    /// <summary>
    /// Write SampleMaster to CSV file
    /// </summary>
    internal static void Write(SampleMaster sampleMaster, CsvWriter csvWriter) {
      sampleMaster.onCsvWrite();
      csvWriter.Write(sampleMaster.Text);
      csvWriter.Write(sampleMaster.NumberWithDefault);
    }
    partial void onCsvWrite();


    /// <summary>
    /// Updates SampleMaster with the provided values
    /// </summary>
    public void Update(string text, int numberWithDefault) {
      var isCancelled = false;
      onUpdating(text, numberWithDefault, ref isCancelled);
      if (isCancelled) return;

      var isChangeDetected = false;
      if (Text!=text) {
        Text = text;
        isChangeDetected = true;
      }
      if (NumberWithDefault!=numberWithDefault) {
        NumberWithDefault = numberWithDefault;
        isChangeDetected = true;
      }
      if (isChangeDetected) {
        onUpdated();
        HasChanged?.Invoke(this);
      }
    }
    partial void onUpdating(string text, int numberWithDefault, ref bool isCancelled);
    partial void onUpdated();


    /// <summary>
    /// Updates this SampleMaster with values from CSV file
    /// </summary>
    internal static void Update(SampleMaster sampleMaster, CsvReader csvReader, DC _) {
      sampleMaster.Text = csvReader.ReadString();
      sampleMaster.NumberWithDefault = csvReader.ReadInt();
      sampleMaster.onCsvUpdate();
    }
    partial void onCsvUpdate();


    /// <summary>
    /// Add sample to SampleX.
    /// </summary>
    internal void AddToSampleX(Sample sample) {
      sampleX.Add(sample);
      onAddedToSampleX(sample);
    }
    partial void onAddedToSampleX(Sample sample);


    /// <summary>
    /// Removes sample from SampleX.
    /// </summary>
    internal void RemoveFromSampleX(Sample sample) {
      //Execute Remove() only when exactly one property in the child still links to this parent. If
      //no property links here (Count=0), the child should not be in the children collection. If
      //more than 1 child property links here, it cannot yet be removed from the children collection.
      var countLinks = 0;
      if (sample.OneMaster==this ) countLinks++;
      if (sample.OtherMaster==this ) countLinks++;
      if (countLinks>1) return;
#if DEBUG
      if (countLinks==0) throw new Exception();
      if (!sampleX.Remove(sample)) throw new Exception();
#else
        sampleX.Remove(sample);
#endif
      onRemovedFromSampleX(sample);
    }
    partial void onRemovedFromSampleX(Sample sample);


    /// <summary>
    /// Removing SampleMaster from DC.Data.SampleMasters is not supported.
    /// </summary>
    public void Remove() {
      throw new NotSupportedException("StorageClass attribute AreInstancesDeletable is false.");
    }


    /// <summary>
    /// Returns property values
    /// </summary>
    public string ToShortString() {
      var returnString =
        $"{Key.ToKeyString()}," +
        $" {Text}," +
        $" {NumberWithDefault}";
      onToShortString(ref returnString);
      return returnString;
    }
    partial void onToShortString(ref string returnString);


    /// <summary>
    /// Returns all property names and values
    /// </summary>
    public override string ToString() {
      var returnString =
        $"Key: {Key}," +
        $" Text: {Text}," +
        $" SampleX: {SampleX.Count}," +
        $" NumberWithDefault: {NumberWithDefault};";
      onToString(ref returnString);
      return returnString;
    }
    partial void onToString(ref string returnString);
    #endregion
  }


  #region SampleMasterWriter
  //      ------------------

  /// <summary>
  /// Writes a CSV file containing records which can be read back as SampleMaster. Note that the keys of linked objects
  /// need to be provided in Write(), since the data context will not be involved.
  /// </summary>
  public class SampleMasterWriter: IDisposable {

    readonly CsvConfig csvConfig;
    readonly CsvWriter csvWriter;
    int lastKey = int.MinValue;


    /// <summary>
    /// Constructor, will write the SampleMaster header line into the CSV file. Dispose SampleMasterWriter once done.
    /// </summary>
    public SampleMasterWriter(string? fileNamePath, CsvConfig csvConfig, int maxLineCharLenght) {
      this.csvConfig = csvConfig;
      csvWriter = new CsvWriter(fileNamePath, csvConfig, maxLineCharLenght, null, 0);
      var csvHeaderString = Csv.ToCsvHeaderString(SampleMaster.Headers, csvConfig.Delimiter);
      csvWriter.WriteLine(csvHeaderString);
    }


    /// <summary>
    /// Writes the details of one SampleMaster to the CSV file
    /// </summary>
    public void Write(int key, string text, int numberWithDefault = int.MinValue) {
      if (key<0) {
        throw new Exception($"SampleMaster's key {key} needs to be greater equal 0.");
      }
      if (key<=lastKey) {
        throw new Exception($"SampleMaster's key {key} must be greater than the last written SampleMaster's key {lastKey}.");
      }
      lastKey = key;
      csvWriter.WriteFirstLineChar(csvConfig.LineCharAdd);
      csvWriter.Write(key);
      csvWriter.Write(text);
      csvWriter.Write(numberWithDefault);
      csvWriter.WriteEndOfLine();
    }


    #region IDisposable Support
    //      -------------------

    /// <summary>
    /// Executes disposal of SampleMasterWriter exactly once.
    /// </summary>
    public void Dispose() {
      Dispose(true);

      GC.SuppressFinalize(this);
    }


    /// <summary>
    /// Is SampleMasterWriter already exposed ?
    /// </summary>
    protected bool IsDisposed {
      get { return isDisposed==1; }
    }


    int isDisposed = 0;


    /// <summary>
    /// Inheritors should call Dispose(false) from their destructor
    /// </summary>
    protected void Dispose(bool disposing) {
      var wasDisposed = Interlocked.Exchange(ref isDisposed, 1);//prevents that 2 threads dispose simultaneously
      if (wasDisposed==1) return; // already disposed

      csvWriter.Dispose();
    }
    #endregion
  }
  #endregion
}
