//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by StorageClassGenerator
//
//     Do not change code in this file, it will get lost when the file gets 
//     auto generated again. Write your code into ReadOnlyParent.cs.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading;
using Storage;


namespace StorageModel  {


    /// <summary>
    /// Example of a "readonly" Parent, i.e. the parent's properties will not change and the parent will never get
    /// deleted, but it is still possible to add children, but not to remove them.
    /// </summary>
  public partial class ReadOnlyParent: IStorage<ReadOnlyParent> {

    #region Properties
    //      ----------

    /// <summary>
    /// Unique identifier for ReadOnlyParent. Gets set once ReadOnlyParent gets added to DL.Data.
    /// </summary>
    public int Key { get; private set; }
    internal static void SetKey(ReadOnlyParent readOnlyParent, int key) { readOnlyParent.Key = key; }


    /// <summary>
    /// Readonly Text, because class is not updatable
    /// </summary>
    public string Text { get; }


    /// <summary>
    /// List of children
    /// </summary>
    public IReadOnlyList<ReadOnlyChild> ReadOnlyChildren => readOnlyChildren;
    readonly List<ReadOnlyChild> readOnlyChildren;


    /// <summary>
    /// Headers written to first line in CSV file
    /// </summary>
    internal static readonly string[] Headers = {"Text"};


    /// <summary>
    /// None existing ReadOnlyParent
    /// </summary>
    internal static ReadOnlyParent NoReadOnlyParent = new ReadOnlyParent("NoText", isStoring: false);
    #endregion


    #region Events
    //      ------

    /// <summary>
    /// This event will never be raised, but is needed to comply with IStorage.
    /// </summary>
#pragma warning disable 67
    public event Action<ReadOnlyParent>? HasChanged;
#pragma warning restore 67
    #endregion


    #region Constructors
    //      ------------

    /// <summary>
    /// ReadOnlyParent Constructor. If isStoring is true, adds ReadOnlyParent to DL.Data.ReadOnlyParents.
    /// </summary>
    public ReadOnlyParent(string text, bool isStoring = true) {
      Key = StorageExtensions.NoKey;
      Text = text;
      readOnlyChildren = new List<ReadOnlyChild>();
      onConstruct();

      if (isStoring) {
        Store();
      }
    }
    partial void onConstruct();


    /// <summary>
    /// Constructor for ReadOnlyParent read from CSV file
    /// </summary>
    private ReadOnlyParent(int key, CsvReader csvReader, DL context) {
      Key = key;
      Text = csvReader.ReadString();
      readOnlyChildren = new List<ReadOnlyChild>();
      onCsvConstruct(context);
    }
    partial void onCsvConstruct(DL context);


    /// <summary>
    /// New ReadOnlyParent read from CSV file
    /// </summary>
    internal static ReadOnlyParent Create(int key, CsvReader csvReader, DL context) {
      return new ReadOnlyParent(key, csvReader, context);
    }
    #endregion


    #region Methods
    //      -------

    /// <summary>
    /// Adds ReadOnlyParent to DL.Data.ReadOnlyParents. 
    /// </summary>
    public void Store() {
      if (Key>=0) {
        throw new Exception($"ReadOnlyParent can not be stored again in DL.Data, key is {Key} greater equal 0." + Environment.NewLine + ToString());
      }
      onStore();
      DL.Data.ReadOnlyParents.Add(this);
    }
    partial void onStore();


    /// <summary>
    /// Maximal number of UTF8 characters needed to write ReadOnlyParent to CSV file
    /// </summary>
    public const int MaxLineLength = 150;


    /// <summary>
    /// Write ReadOnlyParent to CSV file
    /// </summary>
    internal static void Write(ReadOnlyParent readOnlyParent, CsvWriter csvWriter) {
      readOnlyParent.onCsvWrite();
      csvWriter.Write(readOnlyParent.Text);
    }
    partial void onCsvWrite();


    /// <summary>
    /// Add readOnlyChild to ReadOnlyChildren.
    /// </summary>
    internal void AddToReadOnlyChildren(ReadOnlyChild readOnlyChild) {
      readOnlyChildren.Add(readOnlyChild);
      onAddedToReadOnlyChildren(readOnlyChild);
    }
    partial void onAddedToReadOnlyChildren(ReadOnlyChild readOnlyChild);


    /// <summary>
    /// Removing ReadOnlyParent from DL.Data.ReadOnlyParents is not supported.
    /// </summary>
    public void Remove() {
      throw new NotSupportedException("StorageClass attribute AreInstancesDeletable is false.");
    }


    /// <summary>
    /// Returns property values
    /// </summary>
    public string ToShortString() {
      var returnString =
        $"{Key.ToKeyString()}," +
        $" {Text}";
      onToShortString(ref returnString);
      return returnString;
    }
    partial void onToShortString(ref string returnString);


    /// <summary>
    /// Returns all property names and values
    /// </summary>
    public override string ToString() {
      var returnString =
        $"Key: {Key}," +
        $" Text: {Text}," +
        $" ReadOnlyChildren: {ReadOnlyChildren.Count};";
      onToString(ref returnString);
      return returnString;
    }
    partial void onToString(ref string returnString);
    #endregion
  }


  #region ReadOnlyParentWriter
  //      --------------------

  /// <summary>
  /// Writes a CSV file containing records which can be read back as ReadOnlyParent. Note that the keys of linked objects
  /// need to be provided in Write(), since the data context will not be involved.
  /// </summary>
  public class ReadOnlyParentWriter: IDisposable {

    readonly CsvConfig csvConfig;
    readonly CsvWriter csvWriter;


    /// <summary>
    /// Constructor, will write the ReadOnlyParent header line into the CSV file. Dispose ReadOnlyParentWriter once done.
    /// </summary>
    public ReadOnlyParentWriter(string? fileNamePath, CsvConfig csvConfig, int maxLineCharLenght) {
      this.csvConfig = csvConfig;
      csvWriter = new CsvWriter(fileNamePath, csvConfig, maxLineCharLenght, null, 0);
      var csvHeaderString = Csv.ToCsvHeaderString(ReadOnlyParent.Headers, csvConfig.Delimiter);
      csvWriter.WriteLine(csvHeaderString);
    }


    /// <summary>
    /// Writes the details of one ReadOnlyParent to the CSV file
    /// </summary>
    public void Write(string text) {
      csvWriter.StartNewLine();
      csvWriter.Write(text);
      csvWriter.WriteEndOfLine();
    }


    #region IDisposable Support
    //      -------------------

    /// <summary>
    /// Executes disposal of ReadOnlyParentWriter exactly once.
    /// </summary>
    public void Dispose() {
      Dispose(true);

      GC.SuppressFinalize(this);
    }


    /// <summary>
    /// Is ReadOnlyParentWriter already exposed ?
    /// </summary>
    protected bool IsDisposed {
      get { return isDisposed==1; }
    }


    int isDisposed = 0;


    /// <summary>
    /// Inheritors should call Dispose(false) from their destructor
    /// </summary>
    protected void Dispose(bool disposing) {
      var wasDisposed = Interlocked.Exchange(ref isDisposed, 1);//prevents that 2 threads dispose simultaneously
      if (wasDisposed==1) return; // already disposed

      csvWriter.Dispose();
    }
    #endregion
  }
  #endregion
}
